server:
 port: 8082
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/springdb
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Kdriver
 jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
  show-sql: true
  generate-ddl: false
  hibernate:
    ddl-auot: update
